#### LOCAL PLATFORMIO CONFIGURATION FOR CUT ###################################

[platformio]

# Point PlatformIO to the shared OwnTech assets stored at the repository root.
boards_dir = owntech/boards
monitor_dir = owntech/scripts/monitor

#### COMMON ENVIRONMENT DEFINITIONS ###########################################

[env]

platform = ststm32@19.0.0
framework = zephyr

platform_packages =
    tool-openocd
    tool-dfuutil

#### COMMON BOOTLOADER DEFINITIONS ############################################

[bootloader]

board_build.zephyr.bootloader.header_len = 0x200
board_build.zephyr.bootloader.flash_alignment = 8
board_build.zephyr.bootloader.slot_size = 0x37800
board_build.zephyr.bootloader.secondary_slot = 1

board_upload.offset_address = 0x8047800

targets = mcuboot-image

#### RUNNABLE ENVIRONMENT DEFINITIONS #########################################

[env:STLink]
extends = bootloader

board_build.zephyr.cmake_extra_args = -DBUILD_ENV_NAME=STLink

monitor_filters = recorded_datas

upload_protocol = stlink
debug_tool = custom
debug_server =
    ${platformio.packages_dir}/tool-openocd/bin/openocd
    -f
    ${platformio.packages_dir}/tool-openocd/openocd/scripts/interface/stlink.cfg
    -f
    ${platformio.packages_dir}/tool-openocd/openocd/scripts/target/stm32g4x.cfg
    -c
    init
    -c
    reset run
    -c
    program ${platformio.workspace_dir}/build/STLink/firmware.mcuboot.bin 0x8047800 verify

debug_init_cmds =
    target extended-remote $DEBUG_PORT
    file .pio/build/STLink/firmware.elf
    $INIT_BREAK
    monitor reset run

debug_load_cmds =

extra_scripts =
    pre:owntech/scripts/pre_target_gui_config.py
    pre:owntech/scripts/pre_target_install_bootloader.py
    pre:owntech/scripts/pre_bootloader_common.py
    pre:owntech/scripts/pre_target_examples.py
    pre:owntech/scripts/pre_expert_mode.py
    pre:owntech/scripts/pre_stlink.py
    pre:owntech/scripts/pre_version.py
    pre:owntech/scripts/plot/pre_plot_records.py

[env:USB]
extends = bootloader

board_build.zephyr.cmake_extra_args = -DBUILD_ENV_NAME=USB

monitor_port = hwgrep://2fe3:0100
monitor_filters = recorded_datas

upload_protocol = custom
upload_flags =
    -c
    serial
    image
    upload
upload_command = MCUMGRPATH $UPLOAD_FLAGS $SOURCE

extra_scripts =
    pre:owntech/scripts/pre_target_gui_config.py
    pre:owntech/scripts/pre_bootloader_common.py
    pre:owntech/scripts/pre_bootloader_serial.py
    pre:owntech/scripts/pre_target_examples.py
    pre:owntech/scripts/pre_expert_mode.py
    pre:owntech/scripts/pre_recovery.py
    pre:owntech/scripts/pre_usb.py
    pre:owntech/scripts/plot/pre_plot_records.py
    pre:owntech/scripts/pre_version.py
